jefersson/grails-app/controllers/co/jefersson/nunez/AuthController.groovy
package co.jefersson.nunez

import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.web.util.SavedRequest
import org.apache.shiro.web.util.WebUtils

class AuthController {
    def shiroSecurityManager

    def index = { redirect(action: "login", params: params) }

    def login = {
        return [ username: params.username, rememberMe: (params.rememberMe != null), targetUri: params.targetUri ]
    }

    def signIn = {
        def authToken = new UsernamePasswordToken(params.username, params.password as String)

        // Support for "remember me"
        if (params.rememberMe) {
            authToken.rememberMe = true
        }
        
        // If a controller redirected to this page, redirect back
        // to it. Otherwise redirect to the root URI.
        def targetUri = params.targetUri ?: "/"
        
        // Handle requests saved by Shiro filters.
        SavedRequest savedRequest = WebUtils.getSavedRequest(request)
        if (savedRequest) {
            targetUri = savedRequest.requestURI - request.contextPath
            if (savedRequest.queryString) targetUri = targetUri + '?' + savedRequest.queryString
        }
        
        try{
            // Perform the actual login. An AuthenticationException
            // will be thrown if the username is unrecognised or the
            // password is incorrect.
            SecurityUtils.subject.login(authToken)

            log.info "Redirecting to '${targetUri}'."
            redirect(uri: targetUri)
        }
        catch (AuthenticationException ex){
            // Authentication failed, so display the appropriate message
            // on the login page.
            log.info "Authentication failure for user '${params.username}'."
            flash.message = message(code: "login.failed")

            // Keep the username and "remember me" setting so that the
            // user doesn't have to enter them again.
            def m = [ username: params.username ]
            if (params.rememberMe) {
                m["rememberMe"] = true
            }

            // Remember the target URI too.
            if (params.targetUri) {
                m["targetUri"] = params.targetUri
            }

            // Now redirect back to the login page.
            redirect(action: "login", params: m)
        }
    }

    def signOut = {
        // Log the user out of the application.
        SecurityUtils.subject?.logout()
        webRequest.getCurrentRequest().session = null

        // For now, redirect back to the home page.
        redirect(uri: "/")
    }

    def unauthorized = {
		if(SecurityUtils.subject.isPermitted('role:index')){
			redirect action:'index',controller:'role'
			return
		}
        render "No tiene permisos para acceder a esta página."
    }
}

jefersson/grails-app/views/layouts/main.gsp
<%@ page import="org.apache.shiro.SecurityUtils"%>
<%@ page import="co.jefersson.nunez.User" %>

<!DOCTYPE html>
<html>
	<head>
		
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Demo"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'icon_profile.ico')}" type="image/x-icon">
		
		<asset:stylesheet src="bootstrap.min.css" />
    	<asset:stylesheet src="font-awesome/css/font-awesome.min.css" />
    	
    	<!-- Toastr style -->
    	<asset:stylesheet src="plugins/toastr/toastr.min.css" />
		
		<asset:stylesheet src="animate.css" />
	    <asset:stylesheet src="style.css" />
	    
	    <!-- iCheck -->
    	<asset:stylesheet src="plugins/iCheck/custom.css" />
    	
    	<!-- Chosen -->
    	<asset:stylesheet src="plugins/chosen/chosen.css" />
		
		<!-- Mainly scripts -->
	    <asset:javascript src="jquery-2.1.1.js" />
	    <asset:javascript src="bootstrap.min.js" />
		<asset:javascript src="plugins/metisMenu/jquery.metisMenu.js" />
		<asset:javascript src="plugins/slimscroll/jquery.slimscroll.min.js" />
		
		 <!-- Toastr script -->
	    <asset:javascript src="plugins/toastr/toastr.min.js" />
    
		<!-- iCheck -->
    	<asset:javascript src="plugins/iCheck/icheck.min.js" />
	
	    <!-- Custom and plugin javascript -->
	    <asset:javascript src="inspinia.js" />
	    <asset:javascript src="plugins/pace/pace.min.js" />
	    
	    <!-- Chosen -->
		<asset:javascript src="plugins/chosen/chosen.jquery.js" />
  		
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body class="pace-done skin-1">

    <div id="wrapper">

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element"> <span>
                    		<g:if test="${User.findByUsername(SecurityUtils.subject.principal)}">
                       				<g:if test="${User.findByUsername(SecurityUtils.subject.principal)?.urlPhoto}">
		                         		<img alt="image" class="img-circle" src="${User.findByUsername(SecurityUtils.subject.principal).urlPhoto}" style="width:30%;" />
                        			</g:if>
                        			<g:else>
		                         		<img alt="image" class="img-circle" src="${assetPath(src: 'default-user-image.png')}" style="width:30%;" />
		                         	</g:else>
                      		 </g:if>
                      		 <g:else>
                         		<img alt="image" class="img-circle" src="${assetPath(src: 'default-user-image.png')}" style="width:30%;" />
                         	</g:else>
                         </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> 
                            	<strong class="font-bold">
	                            	<g:if test="${User.findByUsername(SecurityUtils.subject.principal)}">
		                        			${User.findByUsername(SecurityUtils.subject.principal)?.name}
		                      		 </g:if>
                            	</strong>
                             </span></span> </a>
                    </div>
                    <div class="logo-element">
                        
                    </div>
                </li>
                 <g:if test="${SecurityUtils.subject.isPermitted('user:index') || SecurityUtils.subject.isPermitted('role:index')}">
	                <li class="${controllerName == 'user' || controllerName == 'role' ? 'active' : ''}">		
	                    <a href="index.html"><i class="fa fa-users"></i> <span class="nav-label"><g:message code="default.users.label" /></span> <span class="fa arrow"></span></a>
	                    <ul class="nav nav-second-level collapse">
	                    	<shiro:hasPermission permission="user:index">
	                       		<li class="${controllerName == 'user' && actionName == 'index' ? 'active' : ''}"><g:link controller="user" action="index"><g:message code="default.users.label" /></g:link></li>
	                        </shiro:hasPermission>
	                        <shiro:hasPermission permission="role:index">
	                        	<li class="${controllerName == 'role' ? 'active' : ''}">
		                        	<a href="#" ><g:message code="default.profiles.label" /><span class="fa arrow"></span></a>
		                            <ul class="nav nav-third-level">
		                                <li class="${controllerName == 'role' && actionName == 'index' ? 'active' : ''}"><g:link controller="role" action="index"><g:message code="default.profiles.list.label" /></g:link></li>
		                                <li class="${controllerName == 'role' && actionName == 'create' ? 'active' : ''}"><g:link controller="role" action="create"><g:message code="default.profiles.create.label" /></g:link></li>
		                            </ul>
	                            </li>
	                        </shiro:hasPermission>
	                    </ul>
	                </li>
	            </g:if>
            </ul>

        </div>
    </nav>
    	

        <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
			<nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
	        <div class="navbar-header">
	            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
	            <div class="navbar-form-custom">
	                <div class="pull-right">
	                	
	                </div>
	            </div>
	        </div>
	            <ul class="nav navbar-top-links navbar-right">
	                <li>
	                	<g:link action="signOut" controller="auth">
							<i class="fa fa-sign-out"></i> <g:message code="default.logout.label" />
						</g:link>
	                </li>
	            </ul>
	
	        </nav>
        </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-sm-7">
                    <ol class="breadcrumb">
						
                    </ol>
                </div>
            </div>

            <div class="wrapper wrapper-content">
				<g:layoutBody />
            </div>
            
            
            <div class="footer">
                <div class="pull-right">
                   	Demo
                </div>
                <div>
                    <strong>Copyright</strong> Jefersson Nuñez &copy; 2017
                </div>
            </div>

        </div>
        </div>


    

	</body>
</html>

jefersson/grails-app/views/layouts/public.gsp
<%@ page import="org.apache.shiro.SecurityUtils"%>


<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><g:layoutTitle default="Grails" /></title>
    
    <asset:stylesheet src="bootstrap.min.css" />
    <asset:stylesheet src="font-awesome/css/font-awesome.min.css" />
    
    <!-- Toastr style -->
    <asset:stylesheet src="plugins/toastr/toastr.min.css" />
    
    <asset:stylesheet src="animate.css" />
    <asset:stylesheet src="style.css" />
    
    <!-- iCheck -->
    <asset:stylesheet src="plugins/iCheck/custom.css" />
    
    <!-- Chosen -->
    <asset:stylesheet src="plugins/chosen/chosen.css" />

    
     <!-- Mainly scripts -->
    <asset:javascript src="jquery-2.1.1.js" />
    <asset:javascript src="bootstrap.min.js" />
	<asset:javascript src="plugins/metisMenu/jquery.metisMenu.js" />
	<asset:javascript src="plugins/slimscroll/jquery.slimscroll.min.js" />

    <!-- Custom and plugin javascript -->
    <asset:javascript src="inspinia.js" />
    <asset:javascript src="plugins/pace/pace.min.js" />
    
    <!-- Toastr script -->
    <asset:javascript src="plugins/toastr/toastr.min.js" />
    
    <!-- iCheck -->
    <asset:javascript src="plugins/iCheck/icheck.min.js" />
    
    <!-- Chosen -->
	<asset:javascript src="plugins/chosen/chosen.jquery.js" />
	
    <asset:javascript src="application.js" />

 
    <g:layoutHead />
</head>

<body class="pace-done skin-1">

	<div id="wrapper">

		<div class="wrapper wrapper-content">
			<g:layoutBody />
		</div>


		<div class="footer">
			<div class="pull-right">Demo</div>
			<div>
				<strong>Copyright</strong> Jefersson Nava &copy; 2017
			</div>
		</div>

	</div>

</body>

</html>